name: 'Docker Sync'
description: 'Pull an image from one registry and push to another'
branding:
  icon: cloud
  color: blue
inputs:
  source_repository:
    description: the source repository
    required: true
  source_username:
    description: the username for the source registry
    required: false
  source_password:
    description: the password for the source registry
    required: false
  target_repository:
    description: the target repository
    required: true
  target_username:
    description: the username for the target registry
    required: false
  target_password:
    description: the password for the target registry
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
